# Generated by Django 5.1.2 on 2024-10-28 05:35

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=255)),
                ('title_ru', models.CharField(blank=True, max_length=255)),
                ('title_uz', models.CharField(blank=True, max_length=255)),
                ('title_de', models.CharField(blank=True, max_length=255)),
                ('img', models.ImageField(upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='CommentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_uz', models.CharField(blank=True, max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message_eng', models.TextField()),
                ('message_ru', models.TextField(blank=True)),
                ('message_uz', models.TextField(blank=True)),
                ('message_de', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_eng', models.TextField()),
                ('address_ru', models.TextField(blank=True)),
                ('address_uz', models.TextField(blank=True)),
                ('address_de', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_eng', models.CharField(max_length=150)),
                ('title_ru', models.CharField(blank=True, max_length=150)),
                ('title_uz', models.CharField(blank=True, max_length=150)),
                ('title_de', models.CharField(blank=True, max_length=150)),
                ('name_eng', models.TextField()),
                ('name_ru', models.TextField(blank=True)),
                ('name_uz', models.TextField(blank=True)),
                ('name_de', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_uz', models.CharField(blank=True, max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100)),
                ('about_eng', models.CharField(max_length=255)),
                ('about_ru', models.CharField(blank=True, max_length=255)),
                ('about_uz', models.CharField(blank=True, max_length=255)),
                ('about_de', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='recentWork/')),
                ('title_eng', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_uz', models.CharField(blank=True, max_length=200)),
                ('title_de', models.CharField(blank=True, max_length=200)),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=150)),
                ('name_ru', models.CharField(blank=True, max_length=150)),
                ('name_uz', models.CharField(blank=True, max_length=150)),
                ('name_de', models.CharField(blank=True, max_length=150)),
                ('icon', models.ImageField(upload_to='icon/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_eng', models.CharField(max_length=50)),
                ('name_ru', models.CharField(blank=True, max_length=50)),
                ('name_uz', models.CharField(blank=True, max_length=50)),
                ('name_de', models.CharField(blank=True, max_length=50)),
                ('icon', models.ImageField(upload_to='Social Media/')),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_place_eng', models.CharField(max_length=255)),
                ('work_place_ru', models.CharField(blank=True, max_length=255)),
                ('work_place_uz', models.CharField(blank=True, max_length=255)),
                ('work_place_de', models.CharField(blank=True, max_length=255)),
                ('text_eng', models.TextField()),
                ('text_ru', models.TextField(blank=True)),
                ('text_uz', models.TextField(blank=True)),
                ('text_de', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='workPlace/')),
                ('year_start', models.DateField()),
                ('year_end', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
