# Generated by Django 5.1.2 on 2024-11-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pepsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_eng', models.TextField()),
                ('text_ru', models.TextField(blank=True)),
                ('text_uz', models.TextField(blank=True)),
            ],
        ),
    ]
