# Generated by Django 5.1.2 on 2024-11-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_banner_title_de'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pepsi',
        ),
        migrations.AddField(
            model_name='banner',
            name='title_de',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
