# Generated by Django 5.1.2 on 2024-11-02 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_pepsi_banner_title_de'),
        ('hitcount', '0004_auto_20200704_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='hit_count_generic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hitcount.hitcount'),
        ),
    ]
