# Generated by Django 5.1.2 on 2024-11-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recentwork_hit_count_generic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='WorkExperiance',
        ),
        migrations.RenameField(
            model_name='commentform',
            old_name='message_eng',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='commentform',
            old_name='name_eng',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='commentform',
            name='message_de',
        ),
        migrations.RemoveField(
            model_name='commentform',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='commentform',
            name='message_uz',
        ),
        migrations.RemoveField(
            model_name='commentform',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='commentform',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='commentform',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name_eng',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name_uz',
        ),
    ]
