# Generated by Django 5.1.2 on 2024-11-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_education_delete_workexperiance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(max_length=60),
        ),
    ]
